### ISSUE TITLE
Program change only works if Blofeld is on midi channel 1

### ISSUE THREAD

**Issue by metaspace** [MaurizioB/Bigglesworth#3]
First of all, thank you for a nice program! I have one issue though:

Program change messages are always sent on channel 1. If Blofeld midi channel is not 1, program change messages have no effect. 

Suggested resolution: Add a setting in preferences for setting the default midi channel for use with program change messages. Program change midi channel is hard coded here: https://github.com/MaurizioB/Bigglesworth/blob/6103a15cb8e33281085054fe42cd6e1bef46813d/bigglesworth/__init__.py#L659

**Comment by MaurizioB** [comment]
Hi @metaspace and thank you for your report. Sorry I missed that, you're completely right as program sends should be configurable. Also, I think I could actually probe the Blofeld about the current channel setting.
Anyway, I'm in the (long and tiresome) process of rewriting almost everything, the librarian and UI are almost complete, then I'll dig into the MIDI part. Keep an eye on the project, I will hopely push a new pre-release in the next weeks.

**Comment by MaurizioB** [comment]
The issue is solved with the new release (now in the branch dev)
